version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    restart: no

  nsqd:
    image: nsqio/nsq
    command: sh -c "/nsqd --mem-queue-size=0 --lookupd-tcp-address=nsqlookupd:4160 && /nsq_to_file --topic=test --output-dir=/tmp --lookupd-http-address=nsqlookupd:4161"
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    restart: no

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    restart: no